#!/usr/bin/env python3
"""
Phase 12 regtest checker -- terrain and profile built from Python.

Validates:

  no file at all -> a case described entirely in Python -- grid, terrain
                    point cloud and profile -- reproduces the fields the
                    equivalent inputs file produces, BIT FOR BIT. Not
                    close: the point cloud goes through the same
                    inverse-distance interpolation, so anything less
                    would mean there are two code paths where there
                    should be one

  points == file -> terrain from a numpy (n, 3) array and terrain from
                    the CSV those numbers were read out of give identical
                    z_terrain and mask

  table == file  -> the same for userfile mode, where the six-column
                    velocity table is handed in as two (n, 3) arrays

  no leak        -> the dict path ignores ParmParse, so a case that omits
                    a parameter takes the default rather than whatever an
                    earlier case left behind. Phase 10 established this
                    for Grid; terrain.file is the one that would hurt
                    most, since inheriting it silently swaps the terrain
                    under a whole dataset

  errors raise   -> ambiguous or malformed inputs raise ValueError rather
                    than picking a winner or being reshaped

Usage:
    python3 check.py /path/to/fastwindterrain.exe [workdir]

Exits 0 if all cases pass, 1 otherwise (suitable for CI).
"""

import sys
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
GROUP = os.path.basename(HERE)
REGTEST_ROOT = os.path.dirname(HERE)
ROOT = os.path.dirname(REGTEST_ROOT)

WORKDIR = os.path.join(ROOT, "build", "regtests", GROUP)

TERRAIN_CSV = os.path.join(REGTEST_ROOT, "phase8_diagnostics_output",
                           "terrain_hill.csv")
PROFILE_TXT = os.path.join(REGTEST_ROOT, "phase4_bc_direction",
                           "user_profile.txt")

# One case, described once. The checker writes it as an inputs file for
# the executable and as a dict for Python, and requires the two to agree.
#
# Deliberately no anisotropy and no O'Brien: both run inside Solver::Setup
# and would rewrite the velocity, so the plotfile's u0 would no longer be
# the profile a standalone Inflow produces. The comparison has to be
# between the same two things.
NX, NY, NZ = 24, 24, 40
GRID = {
    "n_cell": (NX, NY, NZ),
    "prob_lo": (0.0, 0.0, 0.0),
    "prob_hi": (1000.0, 1000.0, 483.19909696997223),
    "dz0": 4.0,
    "stretching_ratio": 1.05,
    "max_grid_size": 16,
}
INFLOW = {
    "mode": "powerlaw",
    "u_ref": 8.0,
    "v_ref": 6.0,
    "z_ref": 10.0,
    "powerlaw_exponent": 0.14,
    "z0": 0.1,
}


def bindings_available():
    shim = os.path.join(ROOT, "build", "fastwindterrain-py")
    pkg = os.path.join(ROOT, "build", "python", "fastwindterrain",
                       "__init__.py")
    return os.path.isfile(shim) and os.path.isfile(pkg)


def python_exe():
    shim = os.path.join(ROOT, "build", "fastwindterrain-py")
    with open(shim) as f:
        for line in f:
            if line.startswith("exec "):
                return line.split('"')[1]
    raise RuntimeError(f"could not read the interpreter out of {shim}")


def run_py(code):
    env = dict(os.environ)
    env["PYTHONPATH"] = (os.path.join(ROOT, "build", "python")
                         + os.pathsep + env.get("PYTHONPATH", ""))
    return subprocess.run([python_exe(), "-c", code], capture_output=True,
                          text=True, timeout=1800, env=env, cwd=WORKDIR)


def marks(stdout):
    out = {}
    for line in stdout.split("\n"):
        if line.startswith("::"):
            k, _, v = line[2:].partition(" ")
            out[k] = v
    return out


PRELUDE = f"""
import numpy as np
import fastwindterrain as fwt
GRID = {GRID!r}
INFLOW = {INFLOW!r}
TERRAIN_CSV = {TERRAIN_CSV!r}
PROFILE_TXT = {PROFILE_TXT!r}
"""


def write_inputs(path, extra=()):
    with open(path, "w") as f:
        f.write("# generated by the Phase 12 checker\n")
        f.write(f"grid.n_cell  = {' '.join(str(v) for v in GRID['n_cell'])}\n")
        f.write(f"grid.prob_lo = {' '.join(repr(v) for v in GRID['prob_lo'])}\n")
        f.write(f"grid.prob_hi = {' '.join(repr(v) for v in GRID['prob_hi'])}\n")
        f.write(f"grid.dz0 = {GRID['dz0']!r}\n")
        f.write(f"grid.stretching_ratio = {GRID['stretching_ratio']!r}\n")
        f.write(f"grid.max_grid_size = {GRID['max_grid_size']}\n")
        f.write(f"terrain.file = {TERRAIN_CSV}\n")
        for k, v in INFLOW.items():
            # repr() would quote a string, and ParmParse takes the quotes
            # literally -- "'powerlaw'" is not a mode.
            text = v if isinstance(v, str) else repr(v)
            f.write(f"inflow.{k} = {text}\n")
        f.write("poisson.n_projections = 1\n")
        for line in extra:
            f.write(line + "\n")


# ---------------------------------------------------------------------------
# 1. a case with no inputs file at all
# ---------------------------------------------------------------------------

def check_no_file_at_all(exe):
    name = "case built entirely in Python"

    inputs = os.path.join(WORKDIR, "inputs_ref")
    write_inputs(inputs, ["grid.output_format = both",
                          "output.format = plt",
                          "grid.plot_file = plt_ref",
                          "grid.report_file = grid_report_ref.txt"])
    r = subprocess.run([exe, inputs], cwd=WORKDIR, capture_output=True,
                       text=True, timeout=3600)
    assert r.returncode == 0, (
        f"[{name}] the executable failed:\n{r.stdout[-2000:]}")

    # Now the same case from Python, with AMReX initialized with NO
    # arguments -- so ParmParse holds nothing at all and every value has
    # to have come from the dicts.
    r2 = run_py(PRELUDE + """
pts = np.loadtxt(TERRAIN_CSV, delimiter=",", comments="#", skiprows=5)
with fwt.session():
    g = fwt.Grid(GRID)
    t = fwt.Terrain(g, {"points": pts})
    inf = fwt.Inflow(g, t, INFLOW)
    np.save("py_vel.npy", inf.velocity)
    np.save("py_mask.npy", t.mask)
    np.save("py_zterr.npy", t.z_terrain)
    print("::NPOINTS", t.n_points)
    print("::NSOLID", t.n_solid)
""")
    assert r2.returncode == 0, (
        f"[{name}] the Python case failed:\n{r2.stdout[-2500:]}\n"
        f"{r2.stderr[-2000:]}")

    r3 = run_py(f"""
import numpy as np, sys
sys.path.insert(0, {REGTEST_ROOT!r})
from plotfile import Plotfile
pf = Plotfile("plt_ref")
vel = np.load("py_vel.npy")
mask = np.load("py_mask.npy")
zt = np.load("py_zterr.npy")

# u0/v0/w0 are the field before any correction, which is what a
# standalone Inflow produces.
pairs = [("u0", vel[0]), ("v0", vel[1]), ("w0", vel[2]),
         ("mask", mask), ("terrain_z", zt)]
worst = 0.0
n = 0
for pfname, arr in pairs:
    f = pf.field(pfname)
    for k in range({NZ}):
        for j in range(0, {NY}, 4):
            for i in range(0, {NX}, 4):
                a = float(arr[k, j, i]); b = float(f(i, j, k))
                if a != b:
                    worst = max(worst, abs(a - b))
                n += 1
print("::N", n)
print("::WORST", repr(worst))
""")
    assert r3.returncode == 0, (
        f"[{name}] the comparison failed:\n{r3.stdout[-2500:]}\n"
        f"{r3.stderr[-2000:]}")

    m = marks(r3.stdout)
    m2 = marks(r2.stdout)
    assert float(m["WORST"]) == 0.0, (
        f"[{name}] a case built entirely in Python differs from the same "
        f"case built from an inputs file; worst difference {m['WORST']}. "
        f"The point cloud is supposed to go through the same "
        f"interpolation, so this means there are two code paths.")
    assert int(m["N"]) > 2000, (
        f"[{name}] only {m['N']} values were compared")

    print(f"[PASS] {name}  (no inputs file: {m2['NPOINTS']} terrain points "
          f"and a dict; {m['N']} values across 5 fields all exactly equal, "
          f"{m2['NSOLID']} solid cells)")


# ---------------------------------------------------------------------------
# 2. points == file, table == file
# ---------------------------------------------------------------------------

def check_points_match_file(exe):
    name = "numpy points vs the CSV"

    r = run_py(PRELUDE + """
pts = np.loadtxt(TERRAIN_CSV, delimiter=",", comments="#", skiprows=5)
with fwt.session():
    g = fwt.Grid(GRID)
    a = fwt.Terrain(g, {"points": pts})
    b = fwt.Terrain(g, {"file": TERRAIN_CSV})
    print("::NPTS %d %d" % (a.n_points, b.n_points))
    print("::ZT", bool(np.array_equal(a.z_terrain, b.z_terrain)))
    print("::MASK", bool(np.array_equal(a.mask, b.mask)))
    print("::ZMIN", a.z_min == b.z_min)
    print("::ZMAX", a.z_max == b.z_max)

    # The interpolation is not the identity -- if it were, this would
    # pass for the wrong reason.
    print("::VARIES", float(a.z_terrain.max() - a.z_terrain.min()) > 1.0)
""")
    assert r.returncode == 0, (
        f"[{name}] failed:\n{r.stdout[-2500:]}\n{r.stderr[-2000:]}")

    m = marks(r.stdout)
    n_a, n_b = (int(v) for v in m["NPTS"].split())
    assert n_a == n_b > 0, (
        f"[{name}] point counts differ: {n_a} vs {n_b}")
    for key in ("ZT", "MASK", "ZMIN", "ZMAX"):
        assert m[key] == "True", (
            f"[{name}] {key} differs between the point cloud and the file")
    assert m["VARIES"] == "True", (
        f"[{name}] the terrain is flat, so this compared nothing useful")

    print(f"[PASS] {name}  ({n_a} points; z_terrain, mask and the extrema "
          f"all identical)")


def check_table_matches_file(exe):
    name = "numpy velocity table vs the file"

    r = run_py(PRELUDE + """
tab = np.loadtxt(PROFILE_TXT, delimiter=",", comments="#", skiprows=6)
with fwt.session():
    g = fwt.Grid(GRID)
    t = fwt.Terrain(g, {"flat_elevation": 0.0})
    a = fwt.Inflow(g, t, {"mode": "userfile",
                          "points": tab[:, 0:3],
                          "velocity": tab[:, 3:6]})
    b = fwt.Inflow(g, t, {"mode": "userfile", "file": PROFILE_TXT})
    print("::NPTS %d %d" % (a.n_points, b.n_points))
    print("::VEL", bool(np.array_equal(a.velocity, b.velocity)))
    print("::FLUX", a.flux_in == b.flux_in and a.flux_out == b.flux_out)
    print("::NONZERO", float(np.abs(a.velocity).max()) > 0.0)
""")
    assert r.returncode == 0, (
        f"[{name}] failed:\n{r.stdout[-2500:]}\n{r.stderr[-2000:]}")

    m = marks(r.stdout)
    n_a, n_b = (int(v) for v in m["NPTS"].split())
    assert n_a == n_b > 0, f"[{name}] point counts differ: {n_a} vs {n_b}"
    assert m["VEL"] == "True", (
        f"[{name}] the interpolated velocity differs between the table and "
        f"the file")
    assert m["FLUX"] == "True", (
        f"[{name}] the boundary flux diagnostics differ")
    assert m["NONZERO"] == "True", (
        f"[{name}] the field is identically zero, so this compared nothing")

    print(f"[PASS] {name}  ({n_a} velocity points; the interpolated field "
          f"and its flux diagnostics identical)")


# ---------------------------------------------------------------------------
# 3. no ParmParse leak
# ---------------------------------------------------------------------------

def check_no_parmparse_leak(exe):
    """terrain.file is the leak that would hurt most: inheriting it
    silently swaps the terrain under a whole dataset."""
    name = "no ParmParse leak"

    inputs = os.path.join(WORKDIR, "inputs_leak")
    write_inputs(inputs)

    r = run_py(PRELUDE + f"""
fwt.initialize([{'"' + os.path.join(WORKDIR, 'inputs_leak') + '"'}])
g = fwt.Grid(GRID)
# The inputs file sets terrain.file to a 100 m hill. Omitting it here
# must give flat ground, not that hill.
t = fwt.Terrain(g, {{}})
print("::NPOINTS", t.n_points)
print("::NSOLID", t.n_solid)
print("::ZMAX", repr(float(t.z_max)))

# Likewise the profile: the file sets u_ref/v_ref, but a dict that names
# its own must use its own.
inf = fwt.Inflow(g, t, {{"mode": "powerlaw", "u_ref": 1.0, "v_ref": 0.0}})
print("::SPEED", repr(float(inf.speed_ref)))
print("::EXPONENT", repr(float(inf.profile_speed(100.0))))
fwt.finalize()
""")
    assert r.returncode == 0, (
        f"[{name}] failed:\n{r.stdout[-2500:]}\n{r.stderr[-2000:]}")

    m = marks(r.stdout)
    assert int(m["NPOINTS"]) == 0, (
        f"[{name}] the dict omitted terrain points and terrain.file, so the "
        f"ground must be flat -- but {m['NPOINTS']} points were read. The "
        f"inputs file's terrain leaked through ParmParse.")
    assert int(m["NSOLID"]) == 0, (
        f"[{name}] flat ground at elevation 0 has no solid cells, got "
        f"{m['NSOLID']}")
    assert float(m["ZMAX"]) == 0.0, (
        f"[{name}] z_max is {m['ZMAX']}, expected 0.0 for flat ground")
    assert float(m["SPEED"]) == 1.0, (
        f"[{name}] speed_ref is {m['SPEED']}, expected 1.0 from the dict "
        f"rather than 10.0 from the inputs file")

    # The default exponent is 0.14; the inputs file sets 0.14 too, so
    # check something the file does set and the dict does not: z_ref.
    # (1.0 * (100/10)^0.14 = 1.3803...)
    expected = 1.0 * (100.0 / 10.0) ** 0.14
    assert abs(float(m["EXPONENT"]) - expected) < 1e-12, (
        f"[{name}] profile_speed(100) is {m['EXPONENT']}, expected "
        f"{expected} from the dict's own defaults")

    print(f"[PASS] {name}  (terrain.file and the reference wind both taken "
          f"from the dict, not from the ParmParse the inputs file filled)")


# ---------------------------------------------------------------------------
# 4. errors
# ---------------------------------------------------------------------------

def check_errors(exe):
    name = "bad input raises"

    r = run_py(PRELUDE + """
pts = np.loadtxt(TERRAIN_CSV, delimiter=",", comments="#", skiprows=5)
tab = np.loadtxt(PROFILE_TXT, delimiter=",", comments="#", skiprows=6)

def expect(label, fn):
    try:
        fn()
        print("::%s accepted" % label)
    except (ValueError, TypeError):
        print("::%s raised" % label)

with fwt.session():
    g = fwt.Grid(GRID)
    t = fwt.Terrain(g, {"flat_elevation": 0.0})

    expect("BOTH", lambda: fwt.Terrain(g, {"points": pts,
                                           "file": TERRAIN_CSV}))
    expect("TYPO", lambda: fwt.Terrain(g, {"flat_elevaton": 0.0}))
    expect("FLAT_PTS", lambda: fwt.Terrain(g, {"points": pts.reshape(-1)}))
    expect("WIDE_PTS", lambda: fwt.Terrain(g, {"points": tab}))
    expect("EMPTY_PTS", lambda: fwt.Terrain(g, {"points": pts[:0]}))
    expect("BADK", lambda: fwt.Terrain(g, {"points": pts,
                                           "idw_n_neighbors": 0}))
    expect("MISSING_FILE", lambda: fwt.Terrain(g, {"file": "no_such.csv"}))

    expect("CALM", lambda: fwt.Inflow(g, t, {"u_ref": 0.0, "v_ref": 0.0}))
    expect("BADMODE", lambda: fwt.Inflow(g, t, {"mode": "spline",
                                                "u_ref": 1.0}))
    expect("TABLE_WRONG_MODE",
           lambda: fwt.Inflow(g, t, {"mode": "powerlaw", "u_ref": 1.0,
                                     "points": tab[:, 0:3],
                                     "velocity": tab[:, 3:6]}))
    expect("HALF_TABLE",
           lambda: fwt.Inflow(g, t, {"mode": "userfile",
                                     "points": tab[:, 0:3]}))
    expect("USERFILE_NOTHING",
           lambda: fwt.Inflow(g, t, {"mode": "userfile"}))
    expect("BOTH_TABLE",
           lambda: fwt.Inflow(g, t, {"mode": "userfile", "file": PROFILE_TXT,
                                     "points": tab[:, 0:3],
                                     "velocity": tab[:, 3:6]}))

    # Still usable afterwards.
    ok = fwt.Inflow(g, t, {"u_ref": 3.0, "v_ref": 4.0})
    print("::ALIVE", repr(float(ok.speed_ref)))
""")
    assert r.returncode == 0, (
        f"[{name}] the interpreter did not survive:\n{r.stdout[-2500:]}\n"
        f"{r.stderr[-2000:]}")

    m = marks(r.stdout)
    labels = ("BOTH", "TYPO", "FLAT_PTS", "WIDE_PTS", "EMPTY_PTS", "BADK",
              "MISSING_FILE", "CALM", "BADMODE", "TABLE_WRONG_MODE",
              "HALF_TABLE", "USERFILE_NOTHING", "BOTH_TABLE")
    for label in labels:
        assert m.get(label) == "raised", (
            f"[{name}] {label} was {m.get(label)}, expected raised")
    assert m["ALIVE"] == "5.0", (
        f"[{name}] a valid Inflow could not be built afterwards")

    print(f"[PASS] {name}  ({len(labels)} bad inputs all raise, including "
          f"points-and-file together and a table in the wrong mode; the "
          f"interpreter survives every one)")


def main():
    global WORKDIR

    if len(sys.argv) not in (2, 3):
        print(f"usage: {sys.argv[0]} /path/to/fastwindterrain.exe [workdir]")
        return 1

    exe = os.path.abspath(sys.argv[1])
    if not os.path.isfile(exe):
        print(f"executable not found: {exe}")
        return 1

    if len(sys.argv) == 3:
        WORKDIR = os.path.abspath(sys.argv[2])
    os.makedirs(WORKDIR, exist_ok=True)
    print(f"work directory: {WORKDIR}")

    if not bindings_available():
        print("[SKIP] the Python bindings are not built. Configure with "
              "-DFWT_PYTHON=ON to run this group.")
        return 0

    failed = []
    for check in (check_no_file_at_all, check_points_match_file,
                  check_table_matches_file, check_no_parmparse_leak,
                  check_errors):
        try:
            check(exe)
        except AssertionError as e:
            print(f"[FAIL] {check.__name__}: {e}")
            failed.append(check.__name__)
        except Exception as e:
            print(f"[ERROR] {check.__name__}: {e}")
            failed.append(check.__name__)

    if failed:
        print(f"\n{len(failed)} Phase 12 regtest case(s) failed: {failed}")
        return 1

    print("\nAll Phase 12 regtest cases passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
