"""
The package as a package: versions in step, the CLI reachable, the module
laid out the way both build paths claim.

There are three places a version is written -- pyproject.toml, the
``project(... VERSION)`` in CMakeLists.txt, and ``fwt.__version__``,
which the C++ side bakes in from the CMake one. Two of them are
maintained by hand, so they drift, and a wheel labelled 0.1.0 reporting
0.2.0 from inside is the kind of thing nobody notices until a dataset
manifest has to be trusted.
"""

import re
import shutil
import subprocess
import sys

import pytest

import fastwindterrain as fwt
from conftest import REPO


def _pyproject_version():
    text = (REPO / "pyproject.toml").read_text()
    # A regex rather than a TOML parser: tomllib is 3.11+, and this file
    # supports 3.9. The line is generated by nobody and edited by hand,
    # so its shape is stable.
    m = re.search(r'^version\s*=\s*"([^"]+)"', text, re.M)
    assert m, "no version = \"...\" line in pyproject.toml"
    return m.group(1)


def _cmake_version():
    text = (REPO / "CMakeLists.txt").read_text()
    m = re.search(r"project\s*\(\s*FastWindTerrain\s+VERSION\s+([0-9.]+)",
                  text)
    assert m, "no project(FastWindTerrain VERSION ...) in CMakeLists.txt"
    return m.group(1)


@pytest.mark.skipif(not (REPO / "pyproject.toml").is_file(),
                    reason="not running from a source checkout")
def test_versions_agree():
    assert _pyproject_version() == _cmake_version() == fwt.__version__, (
        f"pyproject.toml says {_pyproject_version()}, CMakeLists.txt says "
        f"{_cmake_version()}, and the built module reports "
        f"{fwt.__version__}. Bump all three together.")


def test_the_public_surface_is_what_all_says():
    for name in fwt.__all__:
        assert hasattr(fwt, name), f"__all__ names {name}, which is missing"


def test_amrex_version_is_reported():
    assert re.match(r"^\d+\.\d+", fwt.amrex_version()), fwt.amrex_version()


# ---------------------------------------------------------------------------
# The command line
# ---------------------------------------------------------------------------

def test_module_entry_point_prints_usage_without_arguments():
    """``python -m fastwindterrain`` with nothing to run.

    Exit 2 rather than 0: a script that forgot its arguments should fail
    a shell's `set -e`, not look like a successful no-op.
    """
    proc = subprocess.run([sys.executable, "-m", "fastwindterrain"],
                          capture_output=True, text=True)
    assert proc.returncode == 2
    assert "usage:" in proc.stderr


@pytest.mark.skipif(shutil.which("fastwindterrain") is None,
                    reason="console script not installed (in-tree build)")
def test_console_script_is_installed():
    """Present only after `pip install .`; the in-tree build has
    build/fastwindterrain-py instead."""
    proc = subprocess.run(["fastwindterrain"], capture_output=True, text=True)
    assert proc.returncode == 2
    assert "usage:" in proc.stderr


# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------

def test_the_extension_module_sits_inside_the_package():
    """Both build paths must agree about this: the in-tree layout under
    build/python and the wheel's are the same package, or an import that
    works in one fails in the other."""
    assert fwt._fastwindterrain.__name__ == "fastwindterrain._fastwindterrain"


def test_dataset_is_importable_as_a_submodule():
    from fastwindterrain import dataset
    assert dataset.FIELDS
    assert fwt.dataset is dataset


def test_every_public_name_has_a_docstring():
    """These are the bindings' documentation -- there is no separate API
    reference to fall back on."""
    missing = [n for n in fwt.__all__
               if not (getattr(fwt, n).__doc__ or "").strip()
               and n not in ("__version__",)]
    assert missing == [], f"undocumented public names: {missing}"


def test_dataset_functions_are_documented():
    from fastwindterrain import dataset
    missing = [n for n in dataset.__all__
               if not (getattr(dataset, n).__doc__ or "").strip()]
    assert missing == [], f"undocumented dataset names: {missing}"
