"""
Grid built from a Python dict (was regtests/phase10_grid_bindings).

The dict path has to be the REAL path, not a temporary-inputs-file trick.
ParmParse is process-global and persists for the life of an AMReX
initialization, so a case that omits a parameter would inherit whatever
an earlier case set. For one command-line run that never comes up; for a
loop generating a few hundred training samples it is silent corruption
spread across a dataset, with nothing failing anywhere to notice.

The executable's own behaviour is untouched by any of this -- the
undershoot abort, its diagnostic and its nonzero exit status are asserted
by the phase1_grid group, which still runs under run_regtests.py.
"""

import warnings

import pytest

import fastwindterrain as fwt
from conftest import REPO, STRETCHED_TOP


# ---------------------------------------------------------------------------
# The dict path does not read ParmParse
# ---------------------------------------------------------------------------

def test_dict_grid_ignores_parmparse(run_py):
    """Initialize from an inputs file that sets grid.stretching_ratio =
    1.03, then build a Grid from a dict that OMITS it. The default 1.0
    must win.

    The discriminator is chosen so the two answers cannot be confused:
    40 cells of 4 m at ratio 1.0 is exactly 160 m, which matches the
    requested top and warns about nothing. A leaked 1.03 would give
    301.6 m -- an overshoot, a warning, and a different prob_hi.

    Out of process because it needs AMReX initialized from a file, and
    the session fixture has already initialized from nothing.
    """
    inputs = REPO / "regtests" / "phase6_solve_correction" / "inputs_flat"
    r = run_py(f"""
import warnings
import fastwindterrain as fwt
fwt.initialize([{str(inputs)!r}])
with warnings.catch_warnings(record=True) as w:
    warnings.simplefilter("always")
    g = fwt.Grid({{"n_cell": (8, 8, 40), "prob_lo": (0.0, 0.0, 0.0),
                   "prob_hi": (1000.0, 1000.0, 160.0), "dz0": 4.0}})
    print("::RATIO", g.stretching_ratio)
    print("::TOP", g.prob_hi[2])
    print("::NWARN", len(w))
    print("::MGS", g.max_grid_size)
fwt.finalize()
""")

    assert float(r["RATIO"]) == 1.0, (
        "the dict omitted stretching_ratio, so the Grid must take the "
        "default 1.0; it took the value the inputs file left in ParmParse. "
        "Every case in a generation loop after the first would be wrong.")
    assert float(r["TOP"]) == 160.0, "301.6 would mean the ratio leaked"
    assert int(r["NWARN"]) == 0, "an exactly-fitting grid warned"
    assert int(r["MGS"]) == 32, "max_grid_size should be the default 32"


# ---------------------------------------------------------------------------
# A dict grid and a file grid are the same grid
# ---------------------------------------------------------------------------

def test_dict_matches_inputs_file(amrex, grid_params, run_exe, tmp_path):
    """The same grid, described two ways, to the last bit.

    Not to a tolerance: both paths run the same C++ constructor on the
    same doubles, so anything but equality means a value was reparsed or
    rounded on the way in.
    """
    inputs = tmp_path / "inputs_parity"
    g = grid_params
    inputs.write_text(
        "# generated by tests/test_grid.py\n"
        f"grid.n_cell  = {' '.join(str(v) for v in g['n_cell'])}\n"
        f"grid.prob_lo = {' '.join(repr(v) for v in g['prob_lo'])}\n"
        f"grid.prob_hi = {' '.join(repr(v) for v in g['prob_hi'])}\n"
        f"grid.dz0 = {g['dz0']!r}\n"
        f"grid.stretching_ratio = {g['stretching_ratio']!r}\n"
        f"grid.max_grid_size = {g['max_grid_size']}\n"
        "terrain.flat_elevation = 0.0\n"
        "inflow.u_ref = 8.0\ninflow.v_ref = 6.0\n"
        "poisson.n_projections = 1\n"
        "grid.output_format = report\n"
        "grid.report_file = grid_report_parity.txt\n")

    run_exe(inputs)

    z_face_file = {}
    for line in (tmp_path / "grid_report_parity.txt").read_text().splitlines():
        p = line.split()
        if len(p) == 3 and p[0] == "z_face":
            z_face_file[int(p[1])] = float(p[2])

    z_face_py = fwt.Grid(grid_params).z_face

    assert len(z_face_file) == len(z_face_py) == g["n_cell"][2] + 1
    for k, want in sorted(z_face_file.items()):
        assert float(z_face_py[k]) == want, (
            f"z_face[{k}] differs: {float(z_face_py[k])!r} from the dict, "
            f"{want!r} from the inputs file. The two paths must agree "
            f"exactly, not approximately.")


# ---------------------------------------------------------------------------
# Bad input raises; the interpreter survives
# ---------------------------------------------------------------------------

GOOD = {"n_cell": (8, 8, 40), "prob_lo": (0.0, 0.0, 0.0),
        "prob_hi": (1000.0, 1000.0, 160.0), "dz0": 4.0}

BAD_GRIDS = {
    # ParmParse accepts a typo silently and mentions it once at finalize.
    # That is how a misspelled key produces a whole dataset on the wrong
    # grid, so an unknown key has to be refused here.
    "unknown key": dict(GOOD, stretching_ration=1.05),
    "negative dz0": dict(GOOD, dz0=-1.0),
    "zero stretching ratio": dict(GOOD, stretching_ratio=0.0),
    "n_cell is a pair": dict(GOOD, n_cell=(8, 8)),
    "dz0 is a string": dict(GOOD, dz0="four"),
    "inverted domain": dict(GOOD, prob_hi=(1000.0, 1000.0, -5.0)),
    "column undershoots the top": dict(GOOD, prob_hi=(1000.0, 1000.0, 1000.0),
                                       dz0=1.0),
    "dz0 missing": {k: v for k, v in GOOD.items() if k != "dz0"},
}


@pytest.mark.parametrize("params", BAD_GRIDS.values(), ids=list(BAD_GRIDS))
def test_bad_grid_raises(amrex, params):
    """ValueError, not amrex::Abort.

    An abort would take the interpreter with it, which in a generation
    loop means losing every sample computed so far.
    """
    with pytest.raises(ValueError):
        fwt.Grid(params)


def test_interpreter_survives_bad_grids(amrex):
    """The whole point of raising rather than aborting."""
    for params in BAD_GRIDS.values():
        with pytest.raises(ValueError):
            fwt.Grid(params)
    assert fwt.Grid(GOOD).nz == 40


# ---------------------------------------------------------------------------
# An overshoot is a Python warning
# ---------------------------------------------------------------------------

OVERSHOOT = {"n_cell": (8, 8, 10), "prob_lo": (0.0, 0.0, 0.0),
             "prob_hi": (1000.0, 1000.0, 10.0), "dz0": 4.0}


def test_overshoot_warns_and_adjusts(amrex):
    with pytest.warns(UserWarning, match="overshoots") as caught:
        g = fwt.Grid(OVERSHOOT)
    assert len(caught) == 1
    assert g.prob_hi[2] == 40.0, "the domain top should follow the column"


def test_overshoot_is_promotable_to_an_error(amrex):
    """What a dataset generator does rather than let a silently adjusted
    domain into its samples. A line of stdout could not be promoted."""
    with warnings.catch_warnings():
        warnings.simplefilter("error")
        with pytest.raises(UserWarning):
            fwt.Grid(OVERSHOOT)


def test_exact_fit_is_silent(amrex):
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        fwt.Grid({"n_cell": (8, 8, 10), "prob_lo": (0.0, 0.0, 0.0),
                  "prob_hi": (1000.0, 1000.0, 40.0), "dz0": 4.0})
    assert [str(w.message) for w in caught] == []


# ---------------------------------------------------------------------------
# Many grids in one initialization
# ---------------------------------------------------------------------------

def test_many_grids_in_one_session(amrex):
    """Dataset generation means hundreds of cases inside ONE AMReX
    initialization, each independent of the last."""
    for nz in range(10, 60, 5):
        g = fwt.Grid({"n_cell": (8, 8, nz), "prob_lo": (0.0, 0.0, 0.0),
                      "prob_hi": (1000.0, 1000.0, 4.0 * nz), "dz0": 4.0})
        assert g.nz == nz
        assert g.prob_hi[2] == 4.0 * nz
        assert float(g.z_face[-1]) == pytest.approx(4.0 * nz, abs=1e-9)
        del g


def test_grid_arrays_have_the_right_shapes(amrex, grid_params):
    g = fwt.Grid(grid_params)
    assert g.z_cc.shape == (g.nz,)
    assert g.z_face.shape == (g.nz + 1,)
    assert g.n_cell == tuple(grid_params["n_cell"])
    assert float(g.z_face[-1]) == pytest.approx(STRETCHED_TOP, rel=1e-12)
