"""
Terrain and inflow built from Python, with no file anywhere
(was regtests/phase12_terrain_profile_python).

The terrain arrives as a numpy ``(n, 3)`` point cloud and the inflow as
two ``(n, 3)`` arrays, bypassing the CSV and text readers entirely. The
demand is that this changes nothing: a case described only in Python must
reproduce the file-driven case BIT FOR BIT. Not close -- the point cloud
goes through the same inverse-distance interpolation, so any difference
would mean there are two code paths where there should be one.

Deliberately no anisotropy and no O'Brien in the reference case: both run
inside Solver::Setup and rewrite the velocity, so the plotfile's ``u0``
would no longer be the profile a standalone Inflow produces. The
comparison has to be between the same two things.
"""

import numpy as np
import pytest

import fastwindterrain as fwt
from conftest import REPO, TERRAIN_CSV

PROFILE_TXT = REPO / "regtests" / "phase4_bc_direction" / "user_profile.txt"

NX, NY, NZ = 24, 24, 40
GRID = {
    "n_cell": (NX, NY, NZ),
    "prob_lo": (0.0, 0.0, 0.0),
    "prob_hi": (1000.0, 1000.0, 483.19909696997223),
    "dz0": 4.0,
    "stretching_ratio": 1.05,
    "max_grid_size": 16,
}
INFLOW = {
    "mode": "powerlaw",
    "u_ref": 8.0,
    "v_ref": 6.0,
    "z_ref": 10.0,
    "powerlaw_exponent": 0.14,
    "z0": 0.1,
}


@pytest.fixture(scope="session")
def profile_table():
    """The six-column user profile, as one ``(n, 6)`` array."""
    if not PROFILE_TXT.is_file():                       # pragma: no cover
        pytest.skip(f"profile data not found at {PROFILE_TXT}")
    return np.loadtxt(PROFILE_TXT, delimiter=",", comments="#", skiprows=6)


def write_inputs(path, extra=()):
    """The same case as GRID/INFLOW, as an inputs file."""
    lines = ["# generated by tests/test_terrain_profile.py",
             f"grid.n_cell  = {' '.join(str(v) for v in GRID['n_cell'])}",
             f"grid.prob_lo = {' '.join(repr(v) for v in GRID['prob_lo'])}",
             f"grid.prob_hi = {' '.join(repr(v) for v in GRID['prob_hi'])}",
             f"grid.dz0 = {GRID['dz0']!r}",
             f"grid.stretching_ratio = {GRID['stretching_ratio']!r}",
             f"grid.max_grid_size = {GRID['max_grid_size']}",
             f"terrain.file = {TERRAIN_CSV}"]
    for k, v in INFLOW.items():
        # repr() would quote a string, and ParmParse takes the quotes
        # literally -- "'powerlaw'" is not a mode.
        lines.append(f"inflow.{k} = {v if isinstance(v, str) else repr(v)}")
    lines.append("poisson.n_projections = 1")
    # u0 in the output is copied AFTER the surface condition and O'Brien
    # (Solver.cpp), so it is not the raw profile unless both are off. These
    # tests compare a standalone Inflow against it, and their subject is
    # that the point cloud and the profile go through one code path -- the
    # surface condition is phase10_surface_condition's business.
    lines.append("surface.type = none")
    lines.extend(extra)
    path.write_text("\n".join(lines) + "\n")
    return path


# ---------------------------------------------------------------------------
# A case with no inputs file at all
# ---------------------------------------------------------------------------

@pytest.mark.slow
def test_python_only_case_matches_the_inputs_file(amrex, terrain_points,
                                                  run_exe, Plotfile, tmp_path):
    """Grid, terrain point cloud and profile, all from Python, against the
    executable's plotfile for the same case.

    The session's AMReX was initialized with NO arguments, so ParmParse
    holds nothing: every value here has to have come from the dicts.
    """
    inputs = write_inputs(tmp_path / "inputs_ref",
                          ["grid.output_format = both",
                           "output.format = plt",
                           "grid.plot_file = plt_ref",
                           "grid.report_file = grid_report_ref.txt"])
    run_exe(inputs)

    g = fwt.Grid(GRID)
    t = fwt.Terrain(g, {"points": terrain_points})
    inf = fwt.Inflow(g, t, INFLOW)

    pf = Plotfile(str(tmp_path / "plt_ref"))
    # u0/v0/w0 are the field before any correction -- which is what a
    # standalone Inflow produces, and why write_inputs turns the surface
    # condition off.
    pairs = [("u0", inf.velocity[0]), ("v0", inf.velocity[1]),
             ("w0", inf.velocity[2]), ("mask", t.mask),
             ("terrain_z", t.z_terrain)]

    compared = 0
    for pfname, arr in pairs:
        f = pf.field(pfname)
        for k in range(NZ):
            for j in range(0, NY, 4):
                for i in range(0, NX, 4):
                    assert float(arr[k, j, i]) == float(f(i, j, k)), (
                        f"{pfname} at ({i},{j},{k}) differs between the "
                        f"Python-built case and the inputs file. The point "
                        f"cloud goes through the same interpolation, so this "
                        f"means there are two code paths.")
                    compared += 1
    assert compared > 2000
    assert t.n_points > 0 and t.n_solid > 0


# ---------------------------------------------------------------------------
# points == file, table == file
# ---------------------------------------------------------------------------

def test_numpy_points_match_the_csv(amrex, terrain_points):
    g = fwt.Grid(GRID)
    a = fwt.Terrain(g, {"points": terrain_points})
    b = fwt.Terrain(g, {"file": str(TERRAIN_CSV)})

    assert a.n_points == b.n_points > 0
    assert np.array_equal(a.z_terrain, b.z_terrain)
    assert np.array_equal(a.mask, b.mask)
    assert a.z_min == b.z_min
    assert a.z_max == b.z_max
    # The interpolation is not the identity -- if it were, the equalities
    # above would pass for the wrong reason.
    assert float(a.z_terrain.max() - a.z_terrain.min()) > 1.0


def test_numpy_velocity_table_matches_the_file(amrex, profile_table):
    g = fwt.Grid(GRID)
    t = fwt.Terrain(g, {"flat_elevation": 0.0})
    a = fwt.Inflow(g, t, {"mode": "userfile",
                          "points": profile_table[:, 0:3],
                          "velocity": profile_table[:, 3:6]})
    b = fwt.Inflow(g, t, {"mode": "userfile", "file": str(PROFILE_TXT)})

    assert a.n_points == b.n_points > 0
    assert np.array_equal(a.velocity, b.velocity)
    assert a.flux_in == b.flux_in
    assert a.flux_out == b.flux_out
    assert float(np.abs(a.velocity).max()) > 0.0, "the field is all zero"


# ---------------------------------------------------------------------------
# balance_flux
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def slope_points():
    """Ground rising 0 -> 100 m across x, as an (n, 3) point cloud.

    The hill cloud will not do here: it sits in the middle of the domain
    and leaves every lateral face fully open, so the raw profile balances
    exactly and there is nothing to redistribute. A slope blocks the
    bottom of xhi and part of ylo/yhi, which is the case the option is
    for."""
    x = np.linspace(0.0, 1000.0, 51)
    xx, yy = np.meshgrid(x, x, indexing="ij")
    zz = 100.0 * xx / 1000.0
    return np.column_stack([xx.ravel(), yy.ravel(), zz.ravel()])


def test_balance_flux_is_off_by_default(amrex, slope_points):
    g = fwt.Grid(GRID)
    t = fwt.Terrain(g, {"points": slope_points})
    a = fwt.Inflow(g, t, INFLOW)
    b = fwt.Inflow(g, t, dict(INFLOW, balance_flux=0))

    assert not a.flux_balanced and not b.flux_balanced
    assert a.flux_balance_shift == 0.0
    assert np.array_equal(a.velocity, b.velocity)
    # Nothing was done, so the two imbalances are the same number.
    assert a.flux_imbalance_raw == a.flux_imbalance > 0.0


def test_balance_flux_redistributes_over_the_lateral_faces(amrex,
                                                           slope_points):
    """The slope blocks part of the faces, so the raw profile carries a
    net boundary flux. With balance_flux on it must vanish, and the field
    must differ ONLY in the boundary cell layer."""
    g = fwt.Grid(GRID)
    t = fwt.Terrain(g, {"points": slope_points})
    off = fwt.Inflow(g, t, INFLOW)
    on = fwt.Inflow(g, t, dict(INFLOW, balance_flux=1))

    assert off.flux_imbalance > 1.0e-4, "nothing to redistribute"
    assert on.flux_imbalance < 1.0e-12
    assert on.flux_imbalance_raw == off.flux_imbalance
    assert on.flux_balanced and on.flux_balance_shift != 0.0

    # velocity is (3, nz, ny, nx). The interior -- every cell off a
    # lateral face -- is untouched, bit for bit.
    assert np.array_equal(on.velocity[:, :, 1:-1, 1:-1],
                          off.velocity[:, :, 1:-1, 1:-1])
    # And w is untouched everywhere: the top takes no share of it.
    assert np.array_equal(on.velocity[2], off.velocity[2])

    # On each lateral face the normal component moved by side * shift,
    # except in solid cells, which stay at zero.
    shift = on.flux_balance_shift
    solid = t.mask == 1.0
    for comp, index, side in ((0, (slice(None), slice(None), 0), -1),
                              (0, (slice(None), slice(None), -1), +1),
                              (1, (slice(None), 0, slice(None)), -1),
                              (1, (slice(None), -1, slice(None)), +1)):
        delta = on.velocity[comp][index] - off.velocity[comp][index]
        fluid = ~solid[index]
        assert np.allclose(delta[fluid], side * shift, rtol=0, atol=1e-12)
        assert np.all(on.velocity[comp][index][solid[index]] == 0.0)


# ---------------------------------------------------------------------------
# No ParmParse leak
# ---------------------------------------------------------------------------

def test_terrain_and_inflow_ignore_parmparse(run_py, tmp_path):
    """``terrain.file`` is the leak that would hurt most: inheriting it
    silently swaps the terrain under a whole dataset, and every field
    still looks perfectly reasonable.

    Out of process because it needs AMReX initialized from a file.
    """
    inputs = write_inputs(tmp_path / "inputs_leak")
    r = run_py(f"""
import numpy as np
import fastwindterrain as fwt
fwt.initialize([{str(inputs)!r}])
g = fwt.Grid({GRID!r})

# The inputs file names a 100 m hill. Omitting it here must give flat
# ground, not that hill.
t = fwt.Terrain(g, {{}})
print("::NPOINTS", t.n_points)
print("::NSOLID", t.n_solid)
print("::ZMAX", repr(float(t.z_max)))

# Likewise the profile: the file sets u_ref/v_ref, but a dict that names
# its own must use its own.
inf = fwt.Inflow(g, t, {{"mode": "powerlaw", "u_ref": 1.0, "v_ref": 0.0}})
print("::SPEED", repr(float(inf.speed_ref)))
print("::AT100", repr(float(inf.profile_speed(100.0))))
fwt.finalize()
""")

    assert int(r["NPOINTS"]) == 0, (
        "the dict omitted both terrain points and terrain.file, so the "
        "ground must be flat -- the inputs file's terrain leaked through "
        "ParmParse")
    assert int(r["NSOLID"]) == 0
    assert float(r["ZMAX"]) == 0.0
    assert float(r["SPEED"]) == 1.0, (
        "speed_ref should come from the dict, not from the inputs file")
    # The dict does not set z_ref, so the default 10 m has to be used
    # rather than the file's: 1.0 * (100/10)^0.14.
    assert float(r["AT100"]) == pytest.approx(
        1.0 * (100.0 / 10.0) ** 0.14, abs=1e-12)


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------

def _bad_terrains(g, pts, tab):
    return {
        # Two sources of truth: picking a winner would be worse than
        # refusing.
        "points and file together": lambda: fwt.Terrain(
            g, {"points": pts, "file": str(TERRAIN_CSV)}),
        "unknown key": lambda: fwt.Terrain(g, {"flat_elevaton": 0.0}),
        "flattened points": lambda: fwt.Terrain(
            g, {"points": pts.reshape(-1)}),
        "six-column points": lambda: fwt.Terrain(g, {"points": tab}),
        "no points at all": lambda: fwt.Terrain(g, {"points": pts[:0]}),
        "zero neighbours": lambda: fwt.Terrain(
            g, {"points": pts, "idw_n_neighbors": 0}),
        "missing file": lambda: fwt.Terrain(g, {"file": "no_such.csv"}),
    }


def _bad_inflows(g, t, tab):
    return {
        "calm reference wind": lambda: fwt.Inflow(
            g, t, {"u_ref": 0.0, "v_ref": 0.0}),
        "unknown mode": lambda: fwt.Inflow(
            g, t, {"mode": "spline", "u_ref": 1.0}),
        "table in the wrong mode": lambda: fwt.Inflow(
            g, t, {"mode": "powerlaw", "u_ref": 1.0,
                   "points": tab[:, 0:3], "velocity": tab[:, 3:6]}),
        "points without velocity": lambda: fwt.Inflow(
            g, t, {"mode": "userfile", "points": tab[:, 0:3]}),
        "userfile with nothing": lambda: fwt.Inflow(
            g, t, {"mode": "userfile"}),
        "table and file together": lambda: fwt.Inflow(
            g, t, {"mode": "userfile", "file": str(PROFILE_TXT),
                   "points": tab[:, 0:3], "velocity": tab[:, 3:6]}),
    }


def test_bad_terrain_and_inflow_raise(amrex, terrain_points, profile_table):
    """Ambiguous or malformed input raises rather than picking a winner
    or being quietly reshaped -- and the interpreter survives all of it,
    which is the point of raising instead of aborting."""
    g = fwt.Grid(GRID)
    t = fwt.Terrain(g, {"flat_elevation": 0.0})

    cases = {}
    cases.update(_bad_terrains(g, terrain_points, profile_table))
    cases.update(_bad_inflows(g, t, profile_table))

    for label, build in cases.items():
        with pytest.raises((ValueError, TypeError)):
            build()

    assert float(fwt.Inflow(g, t, {"u_ref": 3.0, "v_ref": 4.0}).speed_ref) == 5.0
