#!/usr/bin/env python3
# Generated by cases/build_catalogue.py -- do not edit by hand.
"""
Solve the August Complex Fire case and report what the wind did.

    python3 run.py                             # 8 m/s from the southwest
    python3 run.py --speed 12 --direction 315  # a northwesterly
    python3 run.py --plane xz.png              # the mid-y x-z plane
    python3 run.py --figure wind.png            # that, plus a plan view
    python3 run.py --plotfile plt_case         # for VisIt/ParaView/yt

Direction is meteorological: the direction the wind comes FROM, degrees
clockwise from north.

Run prepare.py first -- the terrain file is not committed.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import casegen


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1],
                                formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument("--speed", type=float, default=8.0, metavar="M/S",
                   help="reference wind speed at 10 m")
    p.add_argument("--direction", type=float, default=225.0, metavar="DEG",
                   help="direction the wind comes FROM")
    p.add_argument("--projections", type=int, default=4, metavar="N",
                   help="projection passes")
    p.add_argument("--plane", default=None, metavar="PATH",
                   help="write the mid-y x-z plane here (needs matplotlib)")
    p.add_argument("--figure", default=None, metavar="PATH",
                   help="write a slice-plus-plan-view figure here")
    p.add_argument("--plotfile", default=None, metavar="PATH",
                   help="also write an AMReX plotfile here")
    args = p.parse_args()

    case = casegen.load('august_complex_fire')
    return casegen.run_case(case, wind_speed=args.speed,
                            wind_direction=args.direction,
                            n_projections=args.projections,
                            figure=args.figure, plane=args.plane,
                            plotfile=args.plotfile)


if __name__ == "__main__":
    sys.exit(main())
