#!/usr/bin/env python3
# Generated by cases/build_catalogue.py -- do not edit by hand.
"""
Download the terrain for the Bootleg Fire and derive this case's grid.

    python3 prepare.py                 # download, survey, write terrain.csv
    python3 prepare.py --subsample 2   # every other SRTM post
    python3 prepare.py --no-download   # re-derive the grid from survey.json

The terrain file is large and is NOT committed -- survey.json is, and the
grid is rebuilt from it, so the case is reproducible without a download.

Needs the geo stack:  pip install ".[cases]"
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import casegen


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1],
                                formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument("--subsample", type=int, default=1, metavar="N",
                   help="keep every N-th SRTM post")
    p.add_argument("--no-download", action="store_true",
                   help="re-derive the grid from the committed survey.json")
    p.add_argument("--tif", default=None, metavar="FILE",
                   help="keep the intermediate SRTM GeoTIFF here")
    args = p.parse_args()

    case = casegen.load('bootleg_fire')
    survey = case.prepare(subsample=args.subsample,
                          download=not args.no_download,
                          tif_path=args.tif)
    casegen.print_survey(case, survey)
    return 0


if __name__ == "__main__":
    sys.exit(main())
