#!/usr/bin/env python3
"""
build_catalogue.py -- (re)generate the case folders from the reference CSV.

One folder per fire, each holding a prepare.py that downloads its terrain
and a run.py that solves it. The scripts are generated rather than
hand-written because there are eight of them and one implementation, in
casegen.py; regenerating is how a change to that implementation reaches
every case at once.

Nothing here touches the network, and nothing overwrites a survey.json or a
terrain file -- only the scripts, the README and case.json are (re)written.

Usage:
    python3 cases/build_catalogue.py                 # write the folders
    python3 cases/build_catalogue.py --list          # just show the set
    python3 cases/build_catalogue.py --check-upstream

--check-upstream fetches the two vendored files from wildfire_levelset and
reports whether our copies still match. It is the only thing in this
directory that needs a network, and it is never run automatically.
"""

import argparse
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import casegen  # noqa: E402

# Vendored from https://github.com/hgopalan/wildfire_levelset at these
# blob revisions. --check-upstream diffs against them.
UPSTREAM = {
    "srtm_terrain_reader.py": {
        "url": ("https://raw.githubusercontent.com/hgopalan/"
                "wildfire_levelset/main/tools/srtm_terrain_reader.py"),
        "sha256": ("9261da29bc84cd125280e22466b0d48e"
                   "fb6943a3ea457d8ed767e9c77a06d1a9"),
        "commit": "db9f063e94d0694d2a0254fa8c79e6e3a794fcca",
    },
    "wildfires_reference.csv": {
        "url": ("https://raw.githubusercontent.com/hgopalan/"
                "wildfire_levelset/main/wildfires_reference.csv"),
        "sha256": ("7c9aca3dea218bb568f11d7ab1e89029"
                   "23151a861f076a0249469e4558a4aede"),
        "commit": "8555542d563404c7ac383604f7f49be5ef8c2d64",
    },
}

GENERATED = "# Generated by cases/build_catalogue.py -- do not edit by hand."


# ---------------------------------------------------------------------------
# The per-case scripts
# ---------------------------------------------------------------------------

PREPARE_TEMPLATE = '''#!/usr/bin/env python3
{generated}
"""
Download the terrain for the {name} and derive this case's grid.

    python3 prepare.py                 # download, survey, write terrain.csv
    python3 prepare.py --subsample 2   # every other SRTM post
    python3 prepare.py --no-download   # re-derive the grid from survey.json

The terrain file is large and is NOT committed -- survey.json is, and the
grid is rebuilt from it, so the case is reproducible without a download.

Needs the geo stack:  pip install ".[cases]"
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import casegen


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1],
                                formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument("--subsample", type=int, default=1, metavar="N",
                   help="keep every N-th SRTM post")
    p.add_argument("--no-download", action="store_true",
                   help="re-derive the grid from the committed survey.json")
    p.add_argument("--tif", default=None, metavar="FILE",
                   help="keep the intermediate SRTM GeoTIFF here")
    args = p.parse_args()

    case = casegen.load({slug!r})
    survey = case.prepare(subsample=args.subsample,
                          download=not args.no_download,
                          tif_path=args.tif)
    casegen.print_survey(case, survey)
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

RUN_TEMPLATE = '''#!/usr/bin/env python3
{generated}
"""
Solve the {name} case and report what the wind did.

    python3 run.py                             # 8 m/s from the southwest
    python3 run.py --speed 12 --direction 315  # a northwesterly
    python3 run.py --plane xz.png              # the mid-y x-z plane
    python3 run.py --figure wind.png            # that, plus a plan view
    python3 run.py --plotfile plt_case         # for VisIt/ParaView/yt

Direction is meteorological: the direction the wind comes FROM, degrees
clockwise from north.

Run prepare.py first -- the terrain file is not committed.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import casegen


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1],
                                formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument("--speed", type=float, default=8.0, metavar="M/S",
                   help="reference wind speed at 10 m")
    p.add_argument("--direction", type=float, default=225.0, metavar="DEG",
                   help="direction the wind comes FROM")
    p.add_argument("--projections", type=int, default=4, metavar="N",
                   help="projection passes")
    p.add_argument("--plane", default=None, metavar="PATH",
                   help="write the mid-y x-z plane here (needs matplotlib)")
    p.add_argument("--figure", default=None, metavar="PATH",
                   help="write a slice-plus-plan-view figure here")
    p.add_argument("--plotfile", default=None, metavar="PATH",
                   help="also write an AMReX plotfile here")
    args = p.parse_args()

    case = casegen.load({slug!r})
    return casegen.run_case(case, wind_speed=args.speed,
                            wind_direction=args.direction,
                            n_projections=args.projections,
                            figure=args.figure, plane=args.plane,
                            plotfile=args.plotfile)


if __name__ == "__main__":
    sys.exit(main())
'''

README_TEMPLATE = """\
# {name}

{state}, {year} — {area_ha:,.0f} ha over {duration_days:.0f} days.

A 5 × 5 km domain centred on {lat:.4f}, {lon:.4f}, at 50 m horizontal
resolution ({nx} × {ny} × {nz} cells).

**Why this case is in the catalogue:** {why}

## Use it

```
python3 prepare.py          # download SRTM, write terrain.csv and survey.json
python3 run.py              # solve, 8 m/s from the southwest
```

`terrain.csv` is a megabyte or so and is **not committed**. `survey.json` is,
and the vertical grid is derived from it — so the grid this case uses is
reproducible without a download, and `prepare.py --no-download` rebuilds it.

The domain floor sits at the tile's minimum elevation and the top a
kilometre above its highest ground, so the vertical extent follows this
case's own relief. Elevations are absolute metres above sea level;
horizontal coordinates are local metres on [0, 5000].
"""

WHY = {
    "dixie_fire": "Feather River canyon, on the northern Sierra/Cascade "
                  "transition — extreme relief and strongly canyon-channelled "
                  "flow.",
    "creek_fire": "Sierra National Forest — the high-elevation case, and the "
                  "one that exercises the domain-floor logic hardest.",
    "rim_fire": "Stanislaus National Forest above the Tuolumne canyon — large "
                "relief on a different aspect from Dixie.",
    "august_complex_fire": "Mendocino National Forest, the inner Coast "
                           "Ranges — ground that burns repeatedly.",
    "tubbs_fire": "Sonoma/Napa, in the Diablo wind corridor; the same ground "
                  "reburned in 2020.",
    "thomas_fire": "The Ventura / Santa Ynez front — Santa Ana and sundowner "
                   "winds over steep terrain.",
    "woolsey_fire": "The Santa Monica Mountains — a Santa Ana corridor that "
                    "has burned repeatedly.",
    "bootleg_fire": "Fremont–Winema, the interior Oregon plateau — the "
                    "low-relief contrast to the Sierra cases.",
}


# ---------------------------------------------------------------------------

def write(path, text, executable=False):
    with open(path, "w") as f:
        f.write(text)
    if executable:
        os.chmod(path, 0o755)
    return path


def build(case):
    if not os.path.isdir(case.folder):
        os.makedirs(case.folder)

    write(os.path.join(case.folder, "prepare.py"),
          PREPARE_TEMPLATE.format(generated=GENERATED, name=case.name,
                                  slug=case.slug), executable=True)
    write(os.path.join(case.folder, "run.py"),
          RUN_TEMPLATE.format(generated=GENERATED, name=case.name,
                              slug=case.slug), executable=True)
    write(os.path.join(case.folder, "README.md"),
          README_TEMPLATE.format(
              name=case.name, state=case.state, year=case.year,
              area_ha=case.area_ha, duration_days=case.duration_days,
              lat=case.lat, lon=case.lon,
              nx=casegen.N_CELL[0], ny=casegen.N_CELL[1], nz=casegen.N_CELL[2],
              why=WHY[case.slug]))

    meta = {
        "slug": case.slug, "name": case.name, "state": case.state,
        "year": case.year, "lat": case.lat, "lon": case.lon,
        "area_ha": case.area_ha, "duration_days": case.duration_days,
        "domain_m": casegen.DOMAIN_M,
        "n_cell": list(casegen.N_CELL),
        "download_bbox_deg": case.bbox_deg(),
        "note": ("Generated by cases/build_catalogue.py from "
                 "wildfires_reference.csv; the grid lives in survey.json, "
                 "which prepare.py writes."),
    }
    with open(os.path.join(case.folder, casegen.CASE_FILE), "w") as f:
        json.dump(meta, f, indent=2, sort_keys=True)
        f.write("\n")

    return case.folder


def check_upstream():
    """Have the vendored files changed upstream? Network, on request only."""
    try:
        from urllib.request import urlopen
    except ImportError:                                  # pragma: no cover
        print("no urllib available", file=sys.stderr)
        return 1

    drifted = []
    for name, meta in sorted(UPSTREAM.items()):
        local = os.path.join(HERE, name)
        have = hashlib.sha256(open(local, "rb").read()).hexdigest()
        if have != meta["sha256"]:
            print(f"[LOCAL] {name} differs from the vendored revision "
                  f"({have[:12]} vs {meta['sha256'][:12]}) -- it was edited "
                  f"here")
            drifted.append(name)
            continue
        try:
            remote = hashlib.sha256(urlopen(meta["url"], timeout=30).read()) \
                .hexdigest()
        except Exception as e:                           # pragma: no cover
            print(f"[SKIP]  {name}: could not fetch upstream ({e})")
            continue
        if remote == have:
            print(f"[OK]    {name} matches upstream")
        else:
            print(f"[DRIFT] {name} has changed upstream "
                  f"({have[:12]} here, {remote[:12]} there). Re-vendor it and "
                  f"update UPSTREAM in this file if the change is wanted.")
            drifted.append(name)
    return 1 if drifted else 0


def main():
    p = argparse.ArgumentParser(
        description="(Re)generate the case folders from the reference CSV.")
    p.add_argument("--list", action="store_true",
                   help="show the catalogue and exit")
    p.add_argument("--check-upstream", action="store_true",
                   help="diff the vendored files against wildfire_levelset")
    args = p.parse_args()

    if args.check_upstream:
        return check_upstream()

    cases = casegen.catalogue()
    if args.list:
        for c in cases:
            print(f"{c.slug:22s} {c.state:12s} {c.year}  "
                  f"{c.lat:8.4f} {c.lon:10.4f}  {WHY[c.slug]}")
        return 0

    for c in cases:
        print(f"wrote {os.path.relpath(build(c), os.path.dirname(HERE))}/")
    print(f"\n{len(cases)} case folders. Each needs its terrain downloading:")
    print(f"    python3 cases/{cases[0].slug}/prepare.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
