#!/usr/bin/env python3
"""
build_corpus.py -- survey the reference fires, then split them safely.

Two stages, deliberately separate:

    python3 cases/build_corpus.py --survey          # needs network + geo stack
    python3 cases/build_corpus.py --split           # offline, pure arithmetic

The survey downloads one wide SRTM tile per fire, cuts it into a 3 x 3 grid
of overlapping 5 km windows, screens the site, and writes a small
corpus/<slug>/survey.json holding everything the split needs -- per-window
extremes and terrain descriptors. That file is committed; the tile it came
from (about ten megabytes) is not.

The split reads those surveys and nothing else. So the manifest can be
regenerated, reviewed and tested on a machine with no network, no geo stack
and no tiles, which is what makes the split reproducible rather than
something that happened once on a laptop.

    python3 cases/build_corpus.py --summary         # what the manifest says
    python3 cases/build_corpus.py --survey --only creek_fire --force
"""

import argparse
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import casegen                                              # noqa: E402
import corpus                                               # noqa: E402

HEADER = ("Generated by cases/build_corpus.py from wildfires_reference.csv; "
          "do not edit by hand.")


# ---------------------------------------------------------------------------
# Stage 1: survey
# ---------------------------------------------------------------------------

def survey_site(case, subsample=1, keep_tile=True):
    """Download one site's tile, cut its windows, and describe each of them.

    Everything expensive happens here, once per site. What comes out is a
    few kilobytes that the split stage can work from forever.
    """
    import numpy as np

    folder = corpus.site_dir(case.slug)
    if not os.path.isdir(folder):
        os.makedirs(folder)

    points = case.download_points(subsample=subsample,
                                  half_width=corpus.CORPUS_HALF_WIDTH_M,
                                  extent=corpus.CORPUS_EXTENT_M)
    z = points[:, 2]
    if float(z.max() - z.min()) <= 0.0:
        raise RuntimeError(
            f"{case.slug}: the downloaded tile is perfectly flat (every "
            f"point at {z[0]:.1f} m). Real ground is not, so this is "
            f"missing or nodata elevation data. Nothing has been written.")

    survey = {
        "slug": case.slug,
        "name": case.name,
        "state": case.state,
        "year": case.year,
        "lat": case.lat,
        "lon": case.lon,
        "n_points": int(z.size),
        "subsample": int(subsample),
        "z_min": float(z.min()),
        "z_max": float(z.max()),
        "z_mean": float(z.mean()),
        "relief": float(z.max() - z.min()),
        "sea_fraction": float(np.mean(z <= 0.0)),
        "extent_m": corpus.CORPUS_EXTENT_M,
        "half_width_m": corpus.CORPUS_HALF_WIDTH_M,
        "window_m": corpus.WINDOW_M,
        "stride_m": corpus.WINDOW_STRIDE_M,
        "n_windows_per_side": corpus.N_WINDOWS_PER_SIDE,
        "source": "SRTM1 via cases/srtm_terrain_reader.py",
        "note": HEADER,
    }

    windows = []
    for iw, jw, x0, y0 in corpus.window_offsets():
        wp = corpus.window_points(points, x0, y0)
        zg = corpus.grid_terrain(wp)
        entry = {
            "id": corpus.window_id(case.slug, iw, jw),
            "site": case.slug,
            "i": iw, "j": jw,
            "x0": float(x0), "y0": float(y0),
            "n_points": int(wp.shape[0]),
            # From the point cloud including the halo, which is what the
            # solver's IDW sees and therefore what has to fit in the domain.
            "z_min": float(wp[:, 2].min()),
            "z_max": float(wp[:, 2].max()),
        }
        entry.update(corpus.descriptors(zg))
        # The grid this window would get, recorded now so the split stage
        # never needs the tile back.
        grid = casegen.grid_from_relief(entry["z_min"], entry["z_max"])
        entry["prob_lo_z"] = grid["prob_lo"][2]
        entry["prob_hi_z"] = grid["prob_hi"][2]
        entry["stretching_ratio"] = grid["stretching_ratio"]
        casegen.assert_fits(wp[:, 2], grid["prob_lo"][2], grid["prob_hi"][2],
                            what=f"{entry['id']} terrain")
        windows.append(entry)
    survey["windows"] = windows

    if keep_tile:
        casegen.write_terrain(corpus.tile_path(case.slug), points,
                              header_lines=[
            f"{case.name} ({case.state} {case.year}) at "
            f"{case.lat:.4f}, {case.lon:.4f}",
            f"corpus tile: {corpus.CORPUS_EXTENT_M:.0f} m square plus "
            f"{casegen.HALO_M:.0f} m halo, {corpus.N_WINDOWS_PER_SIDE}x"
            f"{corpus.N_WINDOWS_PER_SIDE} windows of "
            f"{corpus.WINDOW_M:.0f} m at a {corpus.WINDOW_STRIDE_M:.0f} m "
            f"stride",
        ])
    with open(corpus.site_survey_path(case.slug), "w") as f:
        json.dump(survey, f, indent=2, sort_keys=True)
        f.write("\n")
    return survey


def run_survey(args):
    cases = corpus.candidate_sites()
    if args.only:
        wanted = set(args.only)
        cases = [c for c in cases if c.slug in wanted]
        unknown = wanted - {c.slug for c in cases}
        if unknown:
            print(f"no such site: {sorted(unknown)}", file=sys.stderr)
            return 2

    done = failed = skipped = 0
    for n, case in enumerate(cases, 1):
        path = corpus.site_survey_path(case.slug)
        if os.path.isfile(path) and not args.force:
            print(f"[{n:2d}/{len(cases)}] {case.slug:32s} already surveyed")
            skipped += 1
            continue
        t0 = time.time()
        print(f"[{n:2d}/{len(cases)}] {case.slug:32s} ", end="", flush=True)
        try:
            survey = survey_site(case, subsample=args.subsample,
                                 keep_tile=not args.no_tile)
        except Exception as exc:
            # One bad tile must not lose the other twenty-eight surveys.
            print(f"FAILED: {type(exc).__name__}: "
                  f"{str(exc).splitlines()[0][:120]}")
            failed += 1
            continue
        # Screening is the split stage's job; reported here only so a long
        # survey run says what it is collecting.
        ok, reason, kept = corpus.screen_site(survey)
        flag = "" if ok else f"  would be REJECTED: {reason}"
        print(f"{survey['relief']:7.0f} m relief, "
              f"{survey['n_points']:7d} pts, {len(kept)} windows, "
              f"{time.time() - t0:5.1f} s{flag}")
        done += 1

    print(f"\nsurveyed {done}, skipped {skipped}, failed {failed}")
    return 1 if failed else 0


# ---------------------------------------------------------------------------
# Stage 1b: solvability
#
# A window can pass every geometric check and still not be usable. Above
# roughly 55% solid the projection is non-monotone at the operating pass
# count: it ends with MORE divergence than the terrain-following inflow
# started with, in the norm the solve controls. Such a window is not a
# mass-consistent field and does not belong in a training set.
#
# This is a MEASUREMENT, like the survey, and for the same reason: it is
# expensive, it needs the solver, and the judgement made from it belongs in
# the split stage where it can be changed without re-running. The result is
# a few hundred bytes a site and is committed, so the split still rebuilds
# offline.
#
# Recorded PER (window, direction), not per window, because whether the two
# differ is an empirical question and storing the finer thing costs nothing.
# ---------------------------------------------------------------------------

SOLVABILITY_FILE = "solvability.json"


def solvability_path(slug):
    return os.path.join(corpus.site_dir(slug), SOLVABILITY_FILE)


def read_solvability(corpus_dir=None):
    """``{window_id: entry}`` across every site that has been measured."""
    root = corpus_dir or corpus.CORPUS_DIR
    out = {}
    if not os.path.isdir(root):
        return out
    for slug in sorted(os.listdir(root)):
        path = os.path.join(root, slug, SOLVABILITY_FILE)
        if os.path.isfile(path):
            with open(path) as f:
                out.update(json.load(f).get("windows", {}))
    return out


def measure_solvability(manifest, slug, directions, n_projections):
    """Solve every window of one site at every probe direction.

    RECORDS EVERY NORM, and judges none of them. Which norm you look at
    changes the verdict, and not by a little -- over 1 to 16 passes:

        ditch_fire:20    max|div|  .227 .250 .259 .251 .202   humps
                          L2|div|  .0086 .0079 .0074 .0070 .0068   falls
        bootleg_fire:02  max|div|  .042 .037 .029 .019 .012   falls
                          L2|div|  .0075 .0072 .0075 .0079 .0082   rises

    They disagree in opposite directions on the two windows. A max norm is
    dominated by a handful of cells against the immersed boundary; an
    energy norm is what "how mass-consistent is this field" actually means.
    Storing one and calling it convergence would bake a choice nobody had
    made into the corpus, so all of them are stored and the choice stays a
    split-stage judgement that can be changed without re-solving 252
    windows.

        div_fe_before   L-infinity nodal, at setup -- the only "before"
                        available, since diagnose() needs a solved field
        div_fe_after    the same after the solve
        div_l2          energy norm over fluid cells, from Diagnostics
        div_max         cell-centred max, from Diagnostics
        speed_max       so a relative divergence can be formed: a
                        divergence of 0.007 1/s means one thing at 10 m/s
                        and another at 30
        flux_imbalance  net boundary mass error of the CORRECTED field
        du/dv/dw_max    the largest change the projection made to each
                        velocity component, over the fluid, as a fraction
                        of the reference speed
        dspeed_max      the same for the SPEED |U|, which is the physical
                        quantity: components can each move a long way
                        while the speed barely changes, if the correction
                        mostly turns the wind
        speedup_max     max |U| / |U0| over the fluid -- terrain-induced
                        amplification relative to the undisturbed profile
                        AT THE SAME HEIGHT, which is the form the usual
                        rule of thumb takes. Speed-up over complex terrain
                        does not normally exceed 20-30%, so a window well
                        past that is reporting something other than
                        terrain-driven flow. Measured against the profile
                        rather than against the 80 m reference on purpose:
                        the reference is one height, and the power law
                        alone already gives 1.6x it near the domain top.

    The last of those is a different kind of evidence from a divergence
    norm and worth having for that reason: it says how far the projection
    MOVED the field rather than how mass-consistent the result is. A
    correction of a few tenths of the reference wind is the operator doing
    its job over terrain; a correction several times the reference wind is
    the signature of a setup that has gone wrong -- `Poisson.cpp:218`
    records exactly that failure, a 34.8 m/s corrected wind from a 10 m/s
    inflow, from a lambda boundary condition that interacted badly with
    the nodal divergence. Nothing in a divergence norm would have caught
    it.

    ``velocity0`` is the baseline, which is the O'Brien-adjusted inflow --
    ``Solver.cpp:113`` copies it after that adjustment runs -- so this
    measures the projection alone and not O'Brien.
    """
    import numpy as np
    import fastwindterrain as fwt

    ids = [w["id"] for w in manifest["windows"] if w["site"] == slug]
    windows = {}
    for wid in ids:
        rec = {k: [] for k in ("div_fe_before", "div_fe_after", "div_l2",
                               "div_max", "speed_max", "flux_imbalance",
                               "du_max", "dv_max", "dw_max",
                               "dspeed_max", "speedup_max")}
        for d in directions:
            cfg = corpus.window_config(
                manifest, wid, wind_direction=float(d),
                poisson={"n_projections": n_projections})
            s = fwt.Solver(cfg)
            s.setup()
            rec["div_fe_before"].append(float(s.max_divergence_fe))
            s.solve()
            s.diagnose()
            dg = s.diagnostics

            u, v, w = s.velocity
            fluid = s.mask == 0
            speed = np.sqrt(u * u + v * v + w * w)
            finite = bool(np.all(np.isfinite(s.velocity)))

            # A non-finite field is never converged, whatever a norm says.
            rec["div_fe_after"].append(float(s.max_divergence_fe)
                                       if finite else float("inf"))
            rec["div_l2"].append(float(dg["div_l2"]) if finite
                                 else float("inf"))
            rec["div_max"].append(float(dg["div_max"]) if finite
                                  else float("inf"))
            rec["speed_max"].append(float(speed[fluid].max()) if finite
                                    else float("inf"))
            rec["flux_imbalance"].append(float(dg["flux_imbalance"]))

            # How far the projection moved each component, over the fluid,
            # relative to the reference wind.
            u0, v0, w0 = s.velocity0
            for name, a, b in (("du_max", u, u0), ("dv_max", v, v0),
                               ("dw_max", w, w0)):
                rec[name].append(
                    float(np.abs(a[fluid] - b[fluid]).max()
                          / corpus.REFERENCE_SPEED_MS) if finite
                    else float("inf"))

            speed0 = np.sqrt(u0 * u0 + v0 * v0 + w0 * w0)
            rec["dspeed_max"].append(
                float(np.abs(speed[fluid] - speed0[fluid]).max()
                      / corpus.REFERENCE_SPEED_MS) if finite
                else float("inf"))
            # Amplification relative to the undisturbed profile at the same
            # height. Guarded against the near-surface cells where the
            # profile itself is almost zero and the ratio is meaningless.
            live = fluid & (speed0 > 0.1 * corpus.REFERENCE_SPEED_MS)
            rec["speedup_max"].append(
                float((speed[live] / speed0[live]).max())
                if finite and live.any() else float("inf"))

        rec["n_directions"] = len(directions)
        rec["n_converged"] = int(sum(
            1 for a, b in zip(rec["div_fe_after"], rec["div_fe_before"])
            if a < b))
        windows[wid] = rec
    return {
        "note": HEADER,
        "slug": slug,
        "n_projections": n_projections,
        "directions": [float(d) for d in directions],
        "windows": windows,
    }


def run_solvability(args):
    import fastwindterrain as fwt

    manifest = corpus.load_manifest()
    directions = ([float(v) for v in args.directions.split(",")]
                  if args.directions else list(corpus.WIND_DIRECTIONS))

    sites = sorted({w["site"] for w in manifest["windows"]})
    if args.only:
        sites = [s for s in sites if s in set(args.only)]

    n_win = sum(1 for w in manifest["windows"] if w["site"] in set(sites))
    print(f"{n_win} windows x {len(directions)} directions = "
          f"{n_win * len(directions)} solves at {args.n_projections} passes\n")

    failed = 0
    # One session for the whole run: Initialize/Finalize are process-global
    # and a per-site session would be both slower and, on a second open,
    # an error.
    with fwt.session():
        for n, slug in enumerate(sites, 1):
            path = solvability_path(slug)
            if os.path.isfile(path) and not args.force:
                print(f"[{n:2d}/{len(sites)}] {slug:32s} already measured")
                continue
            t0 = time.time()
            print(f"[{n:2d}/{len(sites)}] {slug:32s} ", end="", flush=True)
            entry = measure_solvability(manifest, slug, directions,
                                        args.n_projections)
            # Written per site, so a run killed halfway keeps what it has
            # and --force is not needed to resume.
            with open(path, "w") as f:
                json.dump(entry, f, indent=2, sort_keys=True)
                f.write("\n")
            bad = [w for w, v in entry["windows"].items()
                   if v["n_converged"] < v["n_directions"]]
            failed += len(bad)
            print(f"{len(entry['windows'])} windows, "
                  f"{len(bad)} not fully converged, {time.time() - t0:6.1f} s")

    print(f"\n{failed} window(s) failed at least one direction. "
          f"Run --split to apply the screen.")
    return 0


# ---------------------------------------------------------------------------
# Stage 2: split
# ---------------------------------------------------------------------------

def build_manifest(fractions=None, seed=corpus.DEFAULT_SEED,
                   radius_km=corpus.CLUSTER_RADIUS_KM, corpus_dir=None):
    """Cluster the surveyed sites, split them, and assert nothing leaked.

    Screening comes BEFORE clustering, not after. A rejected site removed
    from an existing split would shift every later assignment, so the split
    would depend on which sites happened to be surveyed at the time. Screen
    first and the manifest is a function of the accepted set alone.
    """
    surveys = corpus.read_site_surveys(corpus_dir or corpus.CORPUS_DIR)
    if not surveys:
        raise RuntimeError(
            "no surveys found under cases/corpus/. Run\n"
            "    python3 cases/build_corpus.py --survey\n"
            "first -- it needs the network and pip install \".[cases]\".")

    # Solvability, if it has been measured. Absent, the split screens on
    # geometry alone and says so in the manifest, so a manifest built
    # before the measurement is distinguishable from one built after it.
    solvability = read_solvability(corpus_dir)

    # Demo-site surveys live in the same directory but are NOT part of the
    # split: they are not in the reference list, take no share of the
    # fractions, and their absence from fold_of is what stops them being
    # trained on. --demo appends them afterwards.
    surveys = {k: v for k, v in surveys.items()
               if k not in corpus.DEMO_SITES}

    rejected, accepted, keep = {}, {}, {}
    for slug, survey in surveys.items():
        ok, reason, kept = corpus.screen_site(survey, solvability=solvability)
        if ok:
            accepted[slug] = survey
            keep[slug] = set(kept)
        else:
            rejected[slug] = reason
    if not accepted:
        raise RuntimeError(f"every surveyed site was rejected: {rejected}")

    by_slug = {c.slug: c for c in corpus.candidate_sites()}
    sites = [by_slug[s] for s in sorted(accepted) if s in by_slug]

    clusters = corpus.cluster_sites(sites, radius_km=radius_km)
    folds = corpus.split_clusters(clusters, fractions=fractions, seed=seed)
    closest = corpus.assert_no_leakage(sites, folds, radius_km=radius_km)
    assigned = corpus.fold_of(folds)

    windows, dropped = [], {}
    for slug in sorted(accepted):
        for w in accepted[slug]["windows"]:
            if w["id"] not in keep[slug]:
                dropped[w["id"]] = corpus.screen_window(
                    w, solvability=solvability.get(w["id"]))[1]
                continue
            entry = dict(w)
            entry["fold"] = assigned[slug]
            windows.append(entry)

    return {
        "note": HEADER,
        "seed": seed,
        "fractions": dict(fractions or corpus.DEFAULT_FRACTIONS),
        "cluster_radius_km": radius_km,
        "window_m": corpus.WINDOW_M,
        "stride_m": corpus.WINDOW_STRIDE_M,
        "n_windows_per_side": corpus.N_WINDOWS_PER_SIDE,
        "n_cell": list(casegen.N_CELL),
        "sites": sorted(accepted),
        "rejected": rejected,
        "dropped_windows": dropped,
        "min_relief_m": corpus.MIN_RELIEF_M,
        # Whether the convergence screen was applied at all. A manifest
        # built before --solvability was run is a weaker artefact than one
        # built after, and the difference must not be invisible.
        "solvability_screened": bool(solvability),
        "n_solvability_measured": len(solvability),
        "clusters": clusters,
        "folds": folds,
        "fold_of": assigned,
        "closest_cross_fold": [round(closest[0], 3), closest[1], closest[2]],
        "descriptor_keys": list(corpus.DESCRIPTOR_KEYS),
        "windows": windows,
    }


def descriptor_coverage(manifest, stream=None):
    """Does the held-out terrain look like the terrain trained on?

    The question a reviewer asks about any unseen-terrain claim, and the
    honest answer is a range per fold rather than a sentence. A test fold
    whose relief runs 200-400 m against a training fold's 50-2000 m is
    interpolation and should be described as such; one that reaches past the
    training range is extrapolation, which is a more interesting result and
    a weaker claim.
    """
    import numpy as np

    out = stream if stream is not None else sys.stdout
    print("\nterrain descriptor coverage "
          "(min - median - max over each fold's windows)", file=out)
    for key in corpus.DESCRIPTOR_KEYS:
        print(f"\n  {key}", file=out)
        for fold in corpus.FOLDS:
            v = np.array([w[key] for w in manifest["windows"]
                          if w["fold"] == fold])
            if v.size == 0:
                continue
            print(f"    {fold:6s} {v.min():10.3f} {np.median(v):10.3f} "
                  f"{v.max():10.3f}", file=out)


def run_demo(args):
    """Survey the demonstration sites and append them to the manifest.

    They are NOT part of the split: they take no share of the fractions,
    carry corpus.DEMO_FOLD, and assert_demo_is_unseen refuses any that sits
    inside the clustering radius of a corpus site of any fold.
    """
    manifest = corpus.load_manifest()
    far = corpus.assert_demo_is_unseen(manifest=manifest)
    print("demo sites, and the nearest corpus terrain to each:")
    for km, slug, near, fold in far:
        print(f"  {slug:16s} {km:7.1f} km from {near} ({fold})")
    print()

    windows = [w for w in manifest["windows"]
               if w.get("fold") != corpus.DEMO_FOLD]
    added = 0
    for case in corpus.demo_sites():
        path = corpus.site_survey_path(case.slug)
        if os.path.isfile(path) and not args.force:
            print(f"{case.slug:16s} already surveyed")
            survey = json.load(open(path))
        else:
            t0 = time.time()
            print(f"{case.slug:16s} downloading ... ", end="", flush=True)
            survey = survey_site(case, subsample=args.subsample,
                                 keep_tile=not args.no_tile)
            print(f"{survey['relief']:.0f} m relief, "
                  f"{time.time() - t0:.1f} s")

        ok, reason, kept = corpus.screen_site(survey)
        if not ok:
            raise RuntimeError(
                f"{case.slug} fails the same screen the corpus uses: "
                f"{reason}. A demonstration site has to clear the bar the "
                f"training data cleared.")

        for w in survey["windows"]:
            if w["id"] not in set(kept):
                continue
            e = dict(w)
            e["fold"] = corpus.DEMO_FOLD
            windows.append(e)
            added += 1

    manifest["windows"] = windows
    manifest["demo_sites"] = sorted(corpus.DEMO_SITES)
    manifest["demo_nearest_km"] = {s: round(km, 1)
                                   for km, s, _, _ in far}
    with open(corpus.MANIFEST, "w") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"\nadded {added} demo windows to "
          f"{os.path.relpath(corpus.MANIFEST, ROOT)}")
    return 0


def run_split(args):
    fractions = None
    if args.fractions:
        parts = [float(v) for v in args.fractions.split(",")]
        if len(parts) != 3:
            print("--fractions wants three numbers: train,val,test",
                  file=sys.stderr)
            return 2
        fractions = dict(zip(corpus.FOLDS, parts))

    manifest = build_manifest(fractions=fractions, seed=args.seed,
                              radius_km=args.radius)
    with open(corpus.MANIFEST, "w") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"wrote {os.path.relpath(corpus.MANIFEST, ROOT)}\n")
    corpus.summarise(manifest)
    descriptor_coverage(manifest)
    return 0


def run_check(args):
    """Solve a sample of windows and confirm the corpus is actually usable.

    The manifest's arithmetic can be perfect and the corpus still broken:
    phase 16A established that the solver never checks terrain against the
    domain, so a window whose floor is wrong comes out entirely fluid or
    entirely solid and writes a plausible plotfile either way. Two hundred
    and fifty-two windows is two hundred and fifty-two chances at that.

    Sampled across folds rather than run whole -- at roughly a minute a
    solve the full corpus is hours -- and the sample is seeded, so a
    failure can be reproduced.
    """
    import random

    import numpy as np
    import fastwindterrain as fwt

    manifest = corpus.load_manifest()
    rng = random.Random(args.seed)
    picked = []
    for fold in corpus.FOLDS:
        ids = corpus.windows_in(manifest, fold)
        picked += rng.sample(ids, min(args.n, len(ids)))

    print(f"solving {len(picked)} of {len(manifest['windows'])} windows at "
          f"{corpus.REFERENCE_SPEED_MS:.0f} m/s, "
          f"{args.direction:.0f} deg, {args.n_projections} passes\n")
    print(f"{'window':22s} {'solid%':>7s} {'|U|max':>8s} {'|w|max':>8s} "
          f"{'div':>18s} {'s':>6s}  checks")

    failures = []
    times = []
    with fwt.session():
        for wid in picked:
            t0 = time.time()
            cfg = corpus.window_config(
                manifest, wid, wind_direction=args.direction,
                poisson={"n_projections": args.n_projections})
            s = fwt.Solver(cfg)
            s.setup()
            before = float(s.max_divergence_fe)
            s.solve()
            dt = time.time() - t0
            times.append(dt)

            mask = s.mask
            fluid = mask == 0
            u, v, w = s.velocity
            speed = np.sqrt(u * u + v * v + w * w)
            after = float(s.max_divergence_fe)
            solid = float((mask == 1).mean())

            bad = []
            if not 0.0 < solid < 1.0:
                bad.append("straddles")
            if not np.all(np.isfinite(s.velocity)):
                bad.append("finite")
            if not after < before:
                bad.append("divergence")
            if not float(np.abs(w[fluid]).max()) > 0.0:
                bad.append("vertical")
            if not float(speed[fluid].max()) > corpus.REFERENCE_SPEED_MS:
                bad.append("speed-up")

            print(f"{wid:22s} {100.0 * solid:6.1f}% "
                  f"{speed[fluid].max():8.2f} {np.abs(w[fluid]).max():8.2f} "
                  f"{before:8.3g}->{after:8.3g} {dt:6.1f}  "
                  f"{'ok' if not bad else 'FAIL ' + ','.join(bad)}")
            if bad:
                failures.append((wid, bad))

    mean = sum(times) / max(1, len(times))
    n_all = len(manifest["windows"])
    print(f"\nmean {mean:.1f} s a solve over {len(times)} windows")
    print(f"the full corpus at {len(corpus.WIND_DIRECTIONS)} directions is "
          f"{n_all} x {len(corpus.WIND_DIRECTIONS)} = "
          f"{n_all * len(corpus.WIND_DIRECTIONS)} solves, about "
          f"{n_all * len(corpus.WIND_DIRECTIONS) * mean / 3600.0:.1f} core-"
          f"hours (speed is free -- see cases/linearity_study.py)")

    if failures:
        print(f"\n{len(failures)} window(s) failed:")
        for wid, bad in failures:
            print(f"  {wid:22s} {', '.join(bad)}")
        return 1
    print("\nAll checks passed.")
    return 0


def run_summary(args):
    del args
    if not os.path.isfile(corpus.MANIFEST):
        print("no manifest yet; run --split", file=sys.stderr)
        return 2
    manifest = corpus.load_manifest()
    corpus.summarise(manifest)
    descriptor_coverage(manifest)
    return 0


# ---------------------------------------------------------------------------

def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--survey", action="store_true",
                      help="download and describe each site (needs network)")
    mode.add_argument("--split", action="store_true",
                      help="cluster and split the surveyed sites (offline)")
    mode.add_argument("--summary", action="store_true",
                      help="print the existing manifest")
    mode.add_argument("--demo", action="store_true",
                      help="survey the demonstration sites and add them to "
                           "the manifest under the demo fold")
    mode.add_argument("--check", action="store_true",
                      help="solve a sample of windows and check them")
    mode.add_argument("--solvability", action="store_true",
                      help="solve every window and record whether the "
                           "projection converges (expensive; needs --split "
                           "afterwards to apply the screen)")

    p.add_argument("--directions", metavar="D,D,...",
                   help="--solvability: probe directions in degrees FROM "
                        "(default: all eight)")

    p.add_argument("-n", type=int, default=3,
                   help="--check: windows to solve per fold (default 3)")
    p.add_argument("--direction", type=float, default=225.0,
                   help="--check: wind direction, degrees FROM (default 225)")
    p.add_argument("--n-projections", type=int, default=corpus.N_PROJECTIONS,
                   help=f"--check and --solvability: projection passes "
                        f"(default {corpus.N_PROJECTIONS}, the operating "
                        f"point the corpus is generated at)")

    p.add_argument("--only", nargs="+", metavar="SLUG",
                   help="survey just these sites")
    p.add_argument("--force", action="store_true",
                   help="re-survey sites that already have a survey.json")
    p.add_argument("--subsample", type=int, default=1,
                   help="take every Nth SRTM point (default 1)")
    p.add_argument("--no-tile", action="store_true",
                   help="do not keep the tile; survey only")
    p.add_argument("--seed", type=int, default=corpus.DEFAULT_SEED,
                   help=f"split seed (default {corpus.DEFAULT_SEED})")
    p.add_argument("--radius", type=float, default=corpus.CLUSTER_RADIUS_KM,
                   help=f"clustering radius in km "
                        f"(default {corpus.CLUSTER_RADIUS_KM:.0f})")
    p.add_argument("--fractions", metavar="TRAIN,VAL,TEST",
                   help="split fractions, e.g. 0.65,0.15,0.20")

    args = p.parse_args(argv)
    if args.survey:
        return run_survey(args)
    if args.split:
        return run_split(args)
    if args.demo:
        return run_demo(args)
    if args.check:
        return run_check(args)
    if args.solvability:
        return run_solvability(args)
    return run_summary(args)


if __name__ == "__main__":
    sys.exit(main())
